/* ============================================================
   GAME LOOP
   ============================================================ */
let lastFrameTime = 0;

function gameLoop(timestamp) {
  G.now = timestamp / 1000;
  const rawDt = G.now - (lastFrameTime || G.now);
  lastFrameTime = G.now;
  G.dt = Math.min(rawDt, 0.05); // cap delta to avoid spiral-of-death

  if (G.state === 'playing') {
    // Poll gamepads and apply to each player
    pollGamepads();
    for (const player of G.players) {
      // Clear gamepad flags each frame (applyGamepadToPlayer sets them if controller is active)
      player.gpThrust = false;
      player.gpFire = false;
      player.gpSpecial = false;
      player.gpLeft = false;
      player.gpRight = false;
      player.gpUp = false;
      player.targetAngleSet = false;
      applyGamepadToPlayer(player);
      updateShip(player, G.dt);
    }
    updateBullets(G.dt);
    updatePlayerMissiles(G.dt);
    updateMissiles(G.dt);
    updateAsteroids(G.dt);
    maybeSpawnAsteroids();
    updateUfos(G.dt);
    updateParticles(G.dt);
    updatePowerups(G.dt);
    checkCollisions();
  }

  // Gamepad Start button → menu actions (works in any state, with debounce)
  pollGamepads();
  const gpStart = (G._gamepads || []).some(gp => applyGamepadToPlayerStartOnly(gp));
  // Debounce: 500ms cooldown between Start presses
  if (gpStart && (G.now - (G._lastStart || 0) > 0.5)) {
    initAudio();
    G._lastStart = G.now;
    if (G.state === 'start') {
      startGame();
    } else if (G.state === 'gameover') {
      restartGame();
    } else if (G.state === 'playing') {
      G.state = 'paused';
      G._pauseTime = G.now;
      document.getElementById('paused-overlay').classList.remove('hidden');
    } else if (G.state === 'paused') {
      G.state = 'playing';
      delete G._pauseTime;
      document.getElementById('paused-overlay').classList.add('hidden');
    }
  }

  // Always update shake and draw
  updateShake(G.dt);

  // Render
  G.ctx.fillStyle = '#000';
  G.ctx.fillRect(0, 0, G.W, G.H);

  G.ctx.save();
  G.ctx.translate(G.shakeX, G.shakeY);

  const t = G.now;
  drawStars(t);

  for (const player of G.players) {
    drawShip(player, t);
  }

  for (const a of G.asteroids) drawAsteroid(a);
  for (const u of G.ufos) drawUfo(u, t);
  for (const m of G.missiles) drawMissile(m);
  drawPlayerMissiles();
  drawBullets();
  drawPowerups(t);
  drawParticles();

  G.ctx.restore();

  updateHUD();
  requestAnimationFrame(gameLoop);
}

/* ============================================================
   INPUT
   ============================================================ */

function onKeyDown(e) {
  // Ignore keyboard events generated by gamepad buttons
  if (e.code && e.code.startsWith('Gamepad')) return;

  // Prevent default for game keys to avoid page scrolling
  if (['Space', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(e.code)) {
    e.preventDefault();
  }

  initAudio();

  if (G.state === 'start' && ['Digit1', 'Digit2', 'Digit3', 'Digit4'].includes(e.code)) {
    setPlayerCount(Number(e.code.slice(-1)));
    startGame();
    return;
  }

  let startedFromTitle = false;

  // Start game from title screen
  if (G.state === 'start') {
    startGame();
    startedFromTitle = true;
  }

  // Restart from game over
  if (!startedFromTitle && G.state === 'gameover' && (e.code === 'KeyR' || e.key === 'Enter' || e.key === ' ')) {
    restartGame();
    return;
  }

  // Pause toggle (keyboard only - gamepad uses Start button)
  if (!startedFromTitle && e.code === 'KeyP') {
    if (G.state === 'playing') {
      G.state = 'paused';
      G._pauseTime = G.now;
      document.getElementById('paused-overlay').classList.remove('hidden');
      return;
    }
    if (G.state === 'paused') {
      G.state = 'playing';
      delete G._pauseTime;
      document.getElementById('paused-overlay').classList.add('hidden');
      return;
    }
  }

  // Restart anytime
  if (!startedFromTitle && e.code === 'KeyR') {
    restartGame();
    return;
  }

  setPlayerKey(e.code, true);
}

function onKeyUp(e) {
  if (e.code && e.code.startsWith('Gamepad')) return;
  setPlayerKey(e.code, false);
}

function setPlayerKey(code, pressed) {
  for (const player of G.players) {
    const controls = PLAYER_CONFIGS[player.id - 1].keys;
    const codes = [controls.left, controls.right, controls.thrust, controls.back, ...controls.fire];
    if (codes.includes(code)) {
      player.keys[code] = pressed;
      break;
    }
  }
}

function setPlayerCount(count) {
  G.selectedPlayers = Math.max(1, Math.min(4, count));
  document.querySelectorAll('#player-select button').forEach(btn => {
    btn.classList.toggle('selected', Number(btn.dataset.players) === G.selectedPlayers);
  });
}

function startGame() {
  document.getElementById('gameover-overlay').classList.add('hidden');
  document.getElementById('start-overlay').classList.add('hidden');
  document.getElementById('paused-overlay').classList.add('hidden');
  resetGame();
  G.state = 'playing';
  G.now = performance.now() / 1000;
  updateHUD();
}

function onPointerStart(e) {
  initAudio();
  if (G.state !== 'start') return;
  if (e.target && typeof e.target.closest === 'function' && e.target.closest('#player-select')) return;
  startGame();
}

/* ============================================================
   RESET / RESTART
   ============================================================ */
function resetGame() {
  G.bullets = [];
  G.playerMissiles = [];
  G.missiles = [];
  G.asteroids = [];
  G.particles = [];
  G.powerups = [];
  G.ufos = [];
  G.nextBossSpawn = 0;
  G.level = 1;
  G.nextAsteroidSpawn = 0;
  G.shakeMag = 0;
  G.shakeX = 0;
  G.shakeY = 0;

  G.players = PLAYER_CONFIGS
    .slice(0, G.selectedPlayers)
    .map(cfg => createPlayer(cfg.id, cfg.color, cfg.accentColor));

  for (const player of G.players) {
    respawnShip(player);
  }

  scheduleNextBossUfo();
  fillInitialAsteroidField();
}

function restartGame() {
  document.getElementById('gameover-overlay').classList.add('hidden');
  document.getElementById('start-overlay').classList.add('hidden');
  document.getElementById('paused-overlay').classList.add('hidden');
  G._lastStart = 0;
  resetGame();
  G.state = 'playing';
  G.now = performance.now() / 1000;
  updateHUD();
}

/* ============================================================
   RESIZE
   ============================================================ */
function onResize() {
  const dpr = window.devicePixelRatio || 1;
  G.canvas.width  = window.innerWidth * dpr;
  G.canvas.height = window.innerHeight * dpr;
  G.canvas.style.width  = window.innerWidth + 'px';
  G.canvas.style.height = window.innerHeight + 'px';
  G.ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  G.W = window.innerWidth;
  G.H = window.innerHeight;
  initStars();
  // Clear and rebuild sprite caches for new size
  Object.keys(spriteCache).forEach(k => delete spriteCache[k]);
  Object.keys(bulletSprites).forEach(k => delete bulletSprites[k]);
  Object.keys(powerupSprites).forEach(k => delete powerupSprites[k]);
  prewarmSprites();
}

/* ============================================================
   INIT
   ============================================================ */
function init() {
  G.canvas = document.getElementById('game');
  G.ctx = G.canvas.getContext('2d');
  onResize();
  prewarmSprites(); // pre-build sprite cache for smooth first frame

  document.addEventListener('keydown', onKeyDown);
  document.addEventListener('keyup', onKeyUp);
  document.addEventListener('pointerdown', onPointerStart);
  document.addEventListener('touchstart', onPointerStart, { passive: true });
  window.addEventListener('resize', onResize);

  document.querySelectorAll('#player-select button').forEach(btn => {
    btn.addEventListener('click', () => {
      initAudio();
      setPlayerCount(Number(btn.dataset.players));
      if (G.state === 'start') startGame();
    });
  });

  // Gamepad connection events
  window.addEventListener('gamepadconnected', e => updateGpStatus());
  window.addEventListener('gamepaddisconnected', () => updateGpStatus());

  // Start the render loop (game state begins as 'start')
  G.now = performance.now() / 1000;
  lastFrameTime = G.now;
  requestAnimationFrame(gameLoop);
}

// Update controller status display on start screen
function updateGpStatus() {
  const el = document.getElementById('gp-status');
  if (!el) return;
  const list = navigator.getGamepads ? navigator.getGamepads() : [];
  const gpcs = [];
  for (let i = 0; i < list.length; i++) {
    if (list[i] && list[i].connected) {
      gpcs.push('P' + (gpcs.length + 1) + ': ' + gpDisplayName(list[i]));
    }
  }
  el.textContent = gpcs.length ? 'Gamepads: ' + gpcs.join('  |  ') : 'No controllers connected';
  el.style.opacity = gpcs.length ? '0.8' : '0.3';
}

// Boot when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}
